bash ./keyphrase/keyphrase.sh a wifi11.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp5.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ble3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi7.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind5.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn9.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn10.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp7.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind7.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp8.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a fpd1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a fpp1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn16.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn8.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind8.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a iner1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ble1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi5.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn12.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi10.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi6.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a fpd3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn15.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a iner3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn6.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfid2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfid4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a fpp2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfid3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn14.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi9.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ble4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp6.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfid1.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind3.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn13.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn5.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a iner4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ble5.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn7.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi8.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ind6.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a rfn4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a iner2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a wifi4.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a nfp9.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a ble2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
bash ./keyphrase/keyphrase.sh a fpd2.txt Porter_Stemmer disable none 4 'tfidf,dispersion,cscore' all_features.tab 
